# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"@\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\"!\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"J\n\x15PrivateMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"H\n\x13GroupMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08group_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"3\n\x0fMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\rStreamRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"A\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"6\n\x0fPresenceRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tis_online\x18\x02 \x01(\x08\"#\n\x10PresenceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x13OnlineUsersResponse\x12\r\n\x05users\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2\xbb\x03\n\x0b\x43hatService\x12\x30\n\x05Login\x12\x12.chat.LoginRequest\x1a\x13.chat.LoginResponse\x12\x33\n\x06Logout\x12\x13.chat.LogoutRequest\x1a\x14.chat.LogoutResponse\x12H\n\x12SendPrivateMessage\x12\x1b.chat.PrivateMessageRequest\x1a\x15.chat.MessageResponse\x12\x44\n\x10SendGroupMessage\x12\x19.chat.GroupMessageRequest\x1a\x15.chat.MessageResponse\x12:\n\x0eStreamMessages\x12\x13.chat.StreamRequest\x1a\x11.chat.ChatMessage0\x01\x12\x38\n\x0eGetOnlineUsers\x12\x0b.chat.Empty\x1a\x19.chat.OnlineUsersResponse\x12?\n\x0eUpdatePresence\x12\x15.chat.PresenceRequest\x1a\x16.chat.PresenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=20
  _globals['_LOGINREQUEST']._serialized_end=70
  _globals['_LOGINRESPONSE']._serialized_start=72
  _globals['_LOGINRESPONSE']._serialized_end=136
  _globals['_LOGOUTREQUEST']._serialized_start=138
  _globals['_LOGOUTREQUEST']._serialized_end=168
  _globals['_LOGOUTRESPONSE']._serialized_start=170
  _globals['_LOGOUTRESPONSE']._serialized_end=203
  _globals['_PRIVATEMESSAGEREQUEST']._serialized_start=205
  _globals['_PRIVATEMESSAGEREQUEST']._serialized_end=279
  _globals['_GROUPMESSAGEREQUEST']._serialized_start=281
  _globals['_GROUPMESSAGEREQUEST']._serialized_end=353
  _globals['_MESSAGERESPONSE']._serialized_start=355
  _globals['_MESSAGERESPONSE']._serialized_end=406
  _globals['_STREAMREQUEST']._serialized_start=408
  _globals['_STREAMREQUEST']._serialized_end=441
  _globals['_CHATMESSAGE']._serialized_start=443
  _globals['_CHATMESSAGE']._serialized_end=508
  _globals['_PRESENCEREQUEST']._serialized_start=510
  _globals['_PRESENCEREQUEST']._serialized_end=564
  _globals['_PRESENCERESPONSE']._serialized_start=566
  _globals['_PRESENCERESPONSE']._serialized_end=601
  _globals['_ONLINEUSERSRESPONSE']._serialized_start=603
  _globals['_ONLINEUSERSRESPONSE']._serialized_end=639
  _globals['_EMPTY']._serialized_start=641
  _globals['_EMPTY']._serialized_end=648
  _globals['_CHATSERVICE']._serialized_start=651
  _globals['_CHATSERVICE']._serialized_end=1094
# @@protoc_insertion_point(module_scope)
